# placeholder to be able to trigger the new workflow
name: Manual Build - Moonbeam

env:
  SUBWASM_VERSION: 0.20.0
  RUST_LOG: subwasm=debug

on:
  workflow_dispatch:
    inputs:
      srtool_tag:
        description: The SRTOOL tag to use
        default: 1.70.0
        required: false
      ref:
        description: The ref to be used for the repo
        default: master
        required: false

jobs:
  build:
    name: Build ${{ matrix.chain }} ${{ github.event.inputs.ref }}
    strategy:
      matrix:
        chain: ["moonriver"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: PureStake/moonbeam
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
